---
title: RHODAN
baseurl: "" 
url: "https://blog.killswitchx7.com/"

exclude: ['/scripts', '/Gemfile', '/Makefile', '/README.md']

permalink: pretty

collections:
  tools:
    output: true

defaults:
  - scope:
      path: '_tools'
    values:
      layout: bin
